CREATE TABLE IF NOT EXISTS iedi.banks (
  id STRING(36) NOT NULL,
  name STRING(255) NOT NULL,
  variations ARRAY<STRING>,
  active BOOL NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
