CREATE TABLE IF NOT EXISTS iedi.niche_media_outlets (
  id INT64 NOT NULL,
  name STRING NOT NULL,
  domain STRING NOT NULL,
  category STRING,
  monthly_visitors INT64 NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
