CREATE TABLE IF NOT EXISTS iedi.analyses (
  id INT64 NOT NULL,
  name STRING NOT NULL,
  query_name STRING NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  custom_period BOOL NOT NULL DEFAULT FALSE,
  status STRING NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
