CREATE TABLE IF NOT EXISTS iedi.mentions (
  id INT64 NOT NULL,
  brandwatch_id STRING NOT NULL,
  categories ARRAY<STRING>,
  title STRING,
  snippet STRING,
  full_text STRING,
  url STRING,
  domain STRING,
  published_date TIMESTAMP,
  sentiment STRING NOT NULL,
  monthly_visitors INT64,
  reach_group STRING,
  title_verified BOOL DEFAULT FALSE,
  subtitle_verified BOOL DEFAULT FALSE,
  relevant_outlet_verified BOOL DEFAULT FALSE,
  niche_outlet_verified BOOL DEFAULT FALSE,
  numerator FLOAT64 DEFAULT 0.0,
  denominator FLOAT64 DEFAULT 0.0,
  score FLOAT64 DEFAULT 0.0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
