-- Insert unified media outlets (relevant + niche)

INSERT INTO iedi.media_outlets (id, name, domain, category, monthly_visitors, is_niche, active, created_at, updated_at) VALUES
-- Relevant media outlets (is_niche = FALSE)
(1, 'Agência Brasil', 'agenciabrasil.ebc.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, 'Band', 'band.uol.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 'BandNews', 'bandnewstv.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 'BBC Brasil', 'bbc.com/portuguese', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 'Bloomberg', 'bloomberg.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 'Bloomberg Línea', 'bloomberglinea.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 'Brasil 247', 'brasil247.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(8, 'Carta Capital', 'cartacapital.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(9, 'CNN Brasil', 'cnnbrasil.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(10, 'Correio Braziliense', 'correiobraziliense.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(11, 'E-Investidor', 'einvestidor.estadao.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(12, 'Época Negócios', 'epocanegocios.globo.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(13, 'Estadão', 'estadao.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(14, 'Exame', 'exame.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(15, 'Folha de S. Paulo', 'folha.uol.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(16, 'Forbes Brasil', 'forbes.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(17, 'G1', 'g1.globo.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(18, 'Globo News', 'g1.globo.com/globonews', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(19, 'Globo Rural', 'g1.globo.com/economia/agronegocios/globo-rural', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(20, 'Infomoney', 'infomoney.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(21, 'Isto É', 'istoe.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(22, 'Isto É Dinheiro', 'istoedinheiro.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(23, 'Jovem Pan', 'jovempan.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(24, 'Metrópoles', 'metropoles.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(25, 'Money Times', 'moneytimes.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(26, 'O Antagonista', 'oantagonista.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(27, 'O Estado de S. Paulo', 'estadao.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(28, 'O Globo', 'oglobo.globo.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(29, 'Poder360', 'poder360.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(30, 'R7', 'r7.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(31, 'Record News', 'recordnews.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(32, 'Reuters Brasil', 'reuters.com/brazil', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(33, 'SBT News', 'sbtnews.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(34, 'Terra', 'terra.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(35, 'UOL', 'uol.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(36, 'UOL Economia', 'economia.uol.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(37, 'Valor Econômico', 'valor.globo.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(38, 'Valor Investe', 'valorinveste.globo.com', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(39, 'Veja', 'veja.abril.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(40, 'Você S/A', 'vocesa.abril.com.br', NULL, NULL, FALSE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),

-- Niche media outlets (is_niche = TRUE)
(1001, 'Brazil Journal', 'braziljournal.com', NULL, 500000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1002, 'Broadcast', 'broadcast.com.br', NULL, 300000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1003, 'Canal Rural', 'canalrural.com.br', NULL, 450000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1004, 'Conjur', 'conjur.com.br', NULL, 800000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1005, 'Contábeis', 'contabeis.com.br', NULL, 600000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1006, 'Convergência Digital', 'convergenciadigital.com.br', NULL, 350000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1007, 'Diário do Comércio', 'diariodocomercio.com.br', NULL, 250000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1008, 'DCI', 'dci.com.br', NULL, 400000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1009, 'Estadão PME', 'pme.estadao.com.br', NULL, 200000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1010, 'Exame PME', 'exame.com/pme', NULL, 300000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1011, 'Gazeta do Povo', 'gazetadopovo.com.br', NULL, 1200000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1012, 'InfoMoney Pro', 'pro.infomoney.com.br', NULL, 150000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1013, 'Jota', 'jota.info', NULL, 900000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1014, 'Mercado & Consumo', 'mercadoeconsumo.com.br', NULL, 180000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1015, 'Neofeed', 'neofeed.com.br', NULL, 220000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1016, 'Notícias Agrícolas', 'noticiasagricolas.com.br', NULL, 550000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1017, 'Pipeline', 'pipeline.com.br', NULL, 280000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1018, 'Seu Dinheiro', 'seudinheiro.com', NULL, 320000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1019, 'StartSe', 'startse.com', NULL, 400000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1020, 'Teletime', 'teletime.com.br', NULL, 270000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1021, 'The Brief', 'thebrief.com.br', NULL, 190000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(1022, 'Você RH', 'vocerh.abril.com.br', NULL, 350000, TRUE, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
