INSERT INTO iedi.relevant_media_outlets (id, name, domain, category, active, created_at, updated_at) VALUES
(1, 'Agência Brasil', 'agenciabrasil.ebc.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, 'Band', 'band.uol.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 'BandNews', 'bandnewstv.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 'BBC Brasil', 'bbc.com/portuguese', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 'Bloomberg', 'bloomberg.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 'Bloomberg Línea', 'bloomberglinea.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 'Brasil 247', 'brasil247.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(8, 'Carta Capital', 'cartacapital.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(9, 'CNN Brasil', 'cnnbrasil.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(10, 'Correio Braziliense', 'correiobraziliense.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(11, 'E-Investidor', 'einvestidor.estadao.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(12, 'Época Negócios', 'epocanegocios.globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(13, 'Estadão', 'estadao.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(14, 'Exame', 'exame.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(15, 'Folha de S. Paulo', 'folha.uol.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(16, 'Forbes Brasil', 'forbes.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(17, 'G1', 'g1.globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(18, 'Globo News', 'g1.globo.com/globonews', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(19, 'Globo Rural', 'g1.globo.com/economia/agronegocios/globo-rural', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(20, 'InfoMoney', 'infomoney.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(21, 'IstoÉ', 'istoe.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(22, 'IstoÉ Dinheiro', 'istoedinheiro.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(23, 'Jovem Pan', 'jovempan.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(24, 'Metrópoles', 'metropoles.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(25, 'Money Times', 'moneytimes.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(26, 'O Antagonista', 'oantagonista.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(27, 'O Globo', 'oglobo.globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(28, 'Poder 360', 'poder360.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(29, 'R7', 'r7.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(30, 'Reuters', 'reuters.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(31, 'Revista Piauí', 'revistapiaui.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(32, 'Safras & Mercado', 'safras.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(33, 'Seu Dinheiro', 'seudinheiro.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(34, 'Terra', 'terra.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(35, 'CNBC', 'cnbc.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(36, 'TV Globo', 'globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(37, 'UOL', 'uol.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(38, 'Valor Econômico', 'valor.globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(39, 'Valor Investe', 'valorinveste.globo.com', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(40, 'Veja', 'veja.abril.com.br', NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
