INSERT INTO iedi.niche_media_outlets (id, name, domain, category, monthly_visitors, active, created_at, updated_at) VALUES
(1, 'Agência Pública', 'apublica.org', NULL, 420000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(2, 'Agência Spotlight', 'agenciaspotlight.com.br', NULL, 50000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(3, 'AzMina', 'azmina.com.br', NULL, 50000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(4, 'Capital Digital', 'capitaldigital.com.br', NULL, 50000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(5, 'Congresso em Foco', 'congressoemfoco.uol.com.br', NULL, 3000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(6, 'Época Negócios', 'epocanegocios.globo.com', NULL, 6000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(7, 'Forbes Brasil', 'forbes.com.br', NULL, 2000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(8, 'Globo News', 'g1.globo.com/globonews', NULL, 313000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(9, 'Globo Rural', 'g1.globo.com/economia/agronegocios/globo-rural', NULL, 150000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(10, 'InfoMoney', 'infomoney.com.br', NULL, 23000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(11, 'Investing.com', 'br.investing.com', NULL, 159000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(12, 'IstoÉ Dinheiro', 'istoedinheiro.com.br', NULL, 3000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(13, 'Le Monde Diplomatique Brasil', 'diplomatique.org.br', NULL, 260000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(14, 'MoneyTimes', 'moneytimes.com.br', NULL, 8000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(15, 'Pequenas Empresas, Grandes Negócios', 'revistapegn.globo.com', NULL, 2000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(16, 'Poder 360', 'poder360.com.br', NULL, 23000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(17, 'Repórter Brasil', 'reporterbrasil.org.br', NULL, 190000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(18, 'Seu Dinheiro', 'seudinheiro.com', NULL, 3000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(19, 'The Brazilian Report', 'brazilian.report', NULL, 210000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(20, 'The Intercept', 'theintercept.com/brasil', NULL, 5000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(21, 'Valor Econômico', 'valor.globo.com', NULL, 14000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
(22, 'Valor Investe', 'valorinveste.globo.com', NULL, 6000000, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
